### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by imaginetheheadline** [franz-net/tic-tac-toe#1]
# Project 1

Nice job, Franz! Great Readme and organisation of files. Code looks quite good. I would have liked the option to turn off the audio or at least turn it down since I have a strange setup that makes things way too loud by default :) My Youtube volume usually sits at about 30%.

I like the easter eggs as well.

## HTML

Nice work. It looks good and clean. Nice use of data attributes for the cell index, and looks like you've got a few "utility" classes for some of your items. Hopefully that was useful :) See CSS below.

I would look into configuring VS Code's Prettier formatting to do a little better with some of these:

```html
<a href="https://www.linkedin.com/in/franzramirez/" target="_blank">LinkedIn </a>|<a
    href="https://github.com/franz-net"
    target="_blank"
>
    GitHub</a
>
```

It looks a little bit weird.

## CSS

CSS looks pretty good!

```css
* {
    box-sizing: border-box;
}
```

Hooray!

```css
position: sticky;
```
Nice find :)

### Utility classes and duplication

I know you asked about using a CSS Framework, and I can see you've got some utility classes like `modal-button-yes`, `modal-button-continue` that help to compose the style of an element. You can look more into what utility classes are to get an idea. https://tailwindcss.com/ is a framework that uses this heavily.

However, you've also got some missed opportunities to remove some duplication, especially in your modals:

```css
#modal-welcome-content {
    background-color: black;
    color: white;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-evenly;
    line-height: 2em;
    width: 80%;
    height: 80%;
    border-radius: 25px;
    padding: 10px;
    border: 3px solid white;
    text-align: center;
}

#modal-score-content {
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    align-items: center;
    width: 80%;
    height: 200px;
    background-color: rgba(0, 0, 0, 0.7);
    color: white;
    text-align: center;
    line-height: 2em;
    border-radius: 25px;
    padding: 10px;
    border: 2px solid white;
}

```

There is a lot of repeating style here that makes me think you really should have a `modal` class that handles all the cimilar style. Is there a reason that the other styles are different? Like one of those has a 2px border, while the other has a 3px border? Would it make sense for these to be the same?

You could then probably also add a few other modal classes. For example:

```css
.modal {
    /* common style */
}

.modal-full-height {
    height: 80%;
}

.modal-small {
    height: 200px;
}
```

This could make your full UI more composable and so reusable :)

### Responsiveness

Responsiveness is simple and great here. Doesn't need too much but adjusts nicely when the window is small

## JavaScript

Nice work keeping all the game data in an object, and having your winning combos in an array.

Your code looks pretty well organised and nice work on documenting the functions. Since you're doing that, you should look into using JSDoc style: https://jsdoc.app/

Nice $ for elements as well. Your variables are named well. I would call `game` as `Game`. A capital letter better represents a sort of "class" or "module" or "group" of related code. In the same spirit, you could call `winningCombos`, `WINNING_COMBOS` which is a common format for constant configuration-type values that are not meant to change.

```js
window.onload = function () {
    welcomeUsers()
}
```

Nice touch.

### Event handlers

I like that you're using event bubbling. However, I think we may need to dial it back a bit. I would only use bubbling if I want to handle the same event in the same way for some group of elements. However, if you're restricting the event bubbling to only particular events, like for a particular button, then I wouldn't do it there. Just apply it directly to the button.

```js
$welcomeModal.addEventListener('click', (event) => {
    if (event.target.classList.contains('button') && event.target.innerText === 'continue') {
```

This would be better as just:

```js
$welcomeContinueButton.addEventListener('click', ... );
```

Here you're not gaining anything by bubbling the event since the if statement restricts it to only that button.

The board element handler is good, cause you want the same action for all the cells, and the alternative is writing a loop.

### Arrowhead anti-pattern

I'll get into some more advanced stuff :)

```js
$boardElement.addEventListener('click', (event) => {
    if (event.target.classList.contains('cell') && event.target.innerHTML === '') {
        let currentPlayer = ''
        for (let key in game) {
            if (key.includes('player')) {
                if (game[key].isTurn) {
                    turnSound.play()
                    event.target.innerText = game[key].sign
                    game.currentgame[parseInt(event.target.dataset.index)] = game[key].sign
                    currentPlayer = key
                    if (!checkState(currentPlayer)) {
                        setTurn()
                        break
                    } else {
                        return
                    }
                }
            }
        }
    }
})
```

This code is an example of what's known as the arrowhead anti-pattern because of it's shape as an arrow head from left to right with the empty space. And there are problems with it when it comes to readability and testing. You end up having a lot of white-space and less space to write lines of code. It makes it harder to test, too because it means there are a lot of different conditions and paths for the code.

Also, I wouldn't use the `for(let key in game)` here. There are only ever going to be two players, so you can simplify that, while keeping the logic:

```js
$boardElement.addEventListener('click', (event) => {
    if (!event.target.classList.contains('cell') || event.target.innerHTML !== '') {
        return;
    }
    let currentPlayer = ''
    for (let playerInfo of [game.player_1, game.player_2]) {
        if (!playerInfo.isTurn) {
            continue;
        }
        turnSound.play()
        event.target.innerText = playerInfo.sign
        game.currentgame[parseInt(event.target.dataset.index)] = playerInfo.sign
        if (!checkState(playerInfo)) {
            setTurn();
        }
        break
    }
})
```

This way your code is not so indented. I would probably change that playerInfo array though. I think it makes the code a bit strange cause you've got a `continue` in one case, and a `break` for the other. These seem redundant. You only need to apply the action for one player.

How about:

```js
$boardElement.addEventListener('click', (event) => {
    if (!event.target.classList.contains('cell') || event.target.innerHTML !== '') {
        return;
    }
    let currentPlayer = game.player_1.isTurn ? game.player1 : game.player2;

    turnSound.play()
    event.target.innerText = currentPlayer.sign
    game.currentgame[parseInt(event.target.dataset.index)] = currentPlayer.sign
    if (!checkState(currentPlayer)) {
        setTurn();
    }
})
```

I would do somethign similar in `setTurn`

### AI

Nice work getting an AI in there, and I see what you mean. It just chooses the next empty cell haha. Have you thought about how it could choose a random empty cell instead?

```js
function aiPlayTurn(player) {
    let boardIndex = game.currentgame.indexOf('')
    $boardCells[boardIndex].innerText = game[player].sign
    game.currentgame[boardIndex] = game[player].sign
    turnSound.play()
    if (!checkState(player)) {
        setTurn()
    } else {
        return
    }
}
```

You don't need to use an empty return as the last statement of a function. Since there is nothing to do afterwards. `return` is the same as `return undefined;` which runs at the end of every function that doesn't have a return statement. Just remove the `else { return }` here.

### Winning Conditions

Nice work on making that super simple with the `winningCombos` array.

### Delays

Generally nice use of delays with `setTimeout`; however, I did feel this was a bit much:

```js
setTimeout(() => {
    announceResult(game[player].name)
}, 800)
```

It made the game feel slightly unresponsive at the end (I don't mean CSS of course). Especially, cause you don't have the same code for a draw.

### Local Storage

Nice work on local storage.
